#!/bin/sh
set -e

SSH_FLAGS="-A -i "/home/vagrant/.ssh/id_rsa_vagrant" -p 2222 -oStrictHostKeyChecking=no"
DOCKER_CONTAINER="seravo_wordpress"

# After boot, once wait for the Docker to start
if [ ! -e /tmp/.dockerwait ]
then
    sleep 15
    touch /tmp/.dockerwait
fi

# Wait for SSH port to become active
while ! nc -z localhost 2222
do
    echo "Waiting for container SSH..."
    sleep 10
done

echo "entering site container... $@"

if [ -n "${DOCKERSHELL_WRAPPER}" ]
then
    ssh ${SSH_FLAGS} root@localhost "$@"
else
    ssh ${SSH_FLAGS} vagrant@localhost "$@"
fi
