#!/bin/sh
set -e

DOCKER_CONTAINER="seravo_wordpress"

echo "dockershell $@"

if [ -n "${DOCKERSHELL_WRAPPER}" ]
then
    exec /usr/bin/docker exec --interactive --user root "${DOCKER_CONTAINER}" "$@"
else
    exec /usr/bin/docker exec --interactive --tty --user vagrant --workdir=/home/vagrant "${DOCKER_CONTAINER}" bash "$@"
fi

