#!/bin/bash
set -e

# Ensure error codes are passed though and not masked by 'tee'
# Note: Use of pipefail requires bash
set -o pipefail

# Execute $0 inside our Docker container with same parameters
#
# This file gets copied to Docker host to add backwards compatibility
# with commands defined in seravo/wordpress:Vagrantfile . Those commands
# have been moved into container, but existing config files try execute
# them directly inside Vagrant host

#echo ""
#echo "WARNING: Your Vagrantfile contains deprecated configuration."
#echo "  Consider upgrading by running"
#echo ""
#echo "      curl -o /data/wordpress/Vagrantfile -fSL \\"
#echo "              https://raw.githubusercontent.com/Seravo/wordpress/master/Vagrantfile"
#echo ""
#echo "  inside your container"
#echo ""
#echo ""

export SCSHELL_WRAPPER=1

# Ensure path exists
mkdir -p /data/log/vagrant

# Log what was run
echo "Ran: '$0 $@'" >> /data/log/vagrant/wp-wrapper.log

/usr/sbin/sc shell "$0" "$@" | tee -a "/data/log/vagrant/wp-wrapper.log"
