#!/bin/bash
set -e

# Execute $0 inside our Docker container with same parameters
#
# This is a copy of wp-wrapper but without the piping to tee, which prevents
# interactive mode from working. Use this wrapper for commands that need to
# retain the interactive tty session to reply to prompts etc.

# Ensure no command runs too fast (e.g. if wp-development-up if very fast to run)
/usr/sbin/sc wait-log-dir

export SCSHELL_WRAPPER=1

# Ensure path exists
mkdir -p /data/log/vagrant

# Log what was run
echo "Ran: '$0 $@'" >> /data/log/vagrant/wp-wrapper.log

/usr/sbin/sc shell "$0" "$@"
