#!/bin/bash
##
# Activate githooks in scripts folder
##

# Source environment if doesn't exist yet
if [ -z $PS1 ]; then
  source /etc/container_environment.sh
fi

# Use /data/wordpress path
cd /data/wordpress/.git/hooks/
# symlink all files from project into git
ln -sf ../../scripts/hooks/* .