#!/usr/bin/env ruby
##
# Push database to production and Search-Replace with details from config.yml
##
require 'yaml'

config_file = File.join('/data/wordpress','config.yml')

if File.exists?(config_file)
  config = YAML.load_file(config_file)
else
  raise 'config.yml was not found. Please provide the needed information for your box in config.yml.'
end

# Gather variables for ssh/scp
port = config['production']['ssh_port'] || config['production']['port']
host = config['production']['domain'] || config['production']['host']
username = config['production']['user'] || config['name']


dumpfile = "vagrant-push-#{Time.now.to_i}.sql"

puts "Backing up earlier db into /data/db/#{dumpfile}..."
system "wp db export /data/db/#{dumpfile} --quiet"

puts "Getting production siteurls for later search-replacing..."
siteurl_development = `wp option get siteurl`.strip
siteurl_production = `ssh -q #{username}@#{host} -p #{port} "wp option get siteurl"`.strip

puts "Log into production and transfer database, this can take a while..."
system "wp db export - | ssh -q #{username}@#{host} -p #{port} 'wp db import -'"

puts "Search-replacing: #{siteurl_development} -> #{siteurl_production}"
system "ssh -q #{username}@#{host} -p #{port} 'wp search-replace #{siteurl_development} #{siteurl_production}' --network | tail -n1"