#!/usr/bin/env ruby
##
# Pull database from production and Search-Replace with details from config.yml
##
require 'yaml'

config_file = File.join('/data/wordpress','config.yml')

if File.exists?(config_file)
  config = YAML.load_file(config_file)
else
  puts "ERROR: config.yml was not found. Please provide the needed information for your box in config.yml."
  exit 1
end

if config['production'].nil?
  puts "ERROR: couldn't pull database because production isn't configured in config.yml"
  exit 2
end

# Gather variables for ssh/scp
port = config['production']['ssh_port'] || config['production']['port']
host = config['production']['domain'] || config['production']['host']
username = config['production']['user'] || config['name']

backupfile = "pre-production-pull-backup-#{Time.now.to_i}.sql"

puts "Saving backup of current development database in /data/db/pre-production-pull-backup.sql..."
system "wp db export #{backupfile}"

puts "Define new and old siteurl for later search-replacing..."
siteurl_development = `wp option get siteurl`.strip
siteurl_production = `ssh -q #{username}@#{host} -p #{port} "wp option get siteurl"`.strip

puts "Pulling database from production with 'wp db export'..."
system "ssh -q #{username}@#{host} -p #{port} 'wp db export - --single-transaction' " +
 "| pv -Wrbp " +
 "| wp db import -"

# Search Replace all but guid because guid is just a name for post
puts "Search-replacing #{siteurl_production} with #{siteurl_development} --skip-columns=guid"
system "wp search-replace #{siteurl_production} #{siteurl_development}"
