#!/usr/bin/env ruby
##
# Pull production uploads with details from config.yml
##
require 'yaml'

config_file = File.join('/data/wordpress','config.yml')

if File.exists?(config_file)
  config = YAML.load_file(config_file)
else
  raise "ERROR: config.yml was not found. Please provide the needed information for your box in config.yml."
end

if config['production'].nil?
  puts "ERROR: couldn't pull uploaded files because production isn't configured in config.yml"
  exit 2
end

# Gather variables for ssh/scp
port = config['production']['ssh_port'] || config['production']['port']
host = config['production']['domain'] || config['production']['host']
username = config['production']['user'] || config['name']

# Rsync source: http://superuser.com/questions/547282/which-is-the-rsync-command-to-smartly-merge-two-folders
puts "Pulling uploads from production with rsync..."
system "rsync -abviuzP -e 'ssh -p #{port}' #{username}@#{host}:#{ENV['WP_CONTENT']}/uploads/ #{ENV['WP_CONTENT']}/uploads"
