#!/usr/bin/env ruby
##
# Pull production database and Search-Replace with details from config.yml
##
require 'yaml'

config_file = File.join('/data/wordpress','config.yml')

if File.exists?(config_file)
  config = YAML.load_file(config_file)
else
  raise "ERROR: config.yml was not found. Please provide the needed information for your box in config.yml."
end

# Gather variables for ssh/scp
port = config['production']['ssh_port'] || config['production']['port']
host = config['production']['domain'] || config['production']['host']
username = config['production']['user'] || config['name']


# Rsync source: http://superuser.com/questions/547282/which-is-the-rsync-command-to-smartly-merge-two-folders
puts "Pushing uploads to production with rsync..."
system "rsync -abviuzP -e 'ssh -p #{port}' #{ENV['WP_CONTENT']}/uploads/ #{username}@#{host}:#{ENV['WP_CONTENT']}/uploads"
