#!/usr/bin/env ruby
##
# Pull production database and Search-Replace with details from config.yml
##
require 'yaml'

config_file = File.join('/data/wordpress','config.yml')

if File.exists?(config_file)
  config = YAML.load_file(config_file)
else
  raise 'config.yml was not found. Please provide the needed information for your box in config.yml.'
end

if config['production'].nil?
  raise "couldn't pull database because production isn't configured in config.yml"
end

# Gather variables for ssh/scp
port = config['production']['ssh_port'] || config['production']['port']
host = config['production']['domain'] || config['production']['host']
username = config['production']['user'] || config['name']

backupfile = "pre-production-pull-backup-#{Time.now.to_i}.sql"

puts "backing up earlier db into /data/db/pre-production-pull-backup.sql..."
system "wp db export #{backupfile}"

siteurl_development = `wp option get siteurl`.strip

puts "Log into production and migrate database..."
system "ssh -q #{username}@#{host} -p #{port} 'wp db export -' | wp db import - "

siteurl_production = `wp option get siteurl`.strip

puts "Search-replacing #{siteurl_production} with #{siteurl_development}"
system "wp search-replace #{siteurl_production} #{siteurl_development}"