#!/bin/bash
##
# wp-watch-logs
##

if [ -z $1 ]
then
  echo "No path given as argument. Using default path."
  SCANPATH='/data/wordpress/htdocs/wp-content/'
else
  SCANPATH=$1
fi

echo "Scanning for .po files in $SCANPATH"

# Find PO files, process each with msgfmt and rename the result to MO
for file in `find $SCANPATH -name "*.po"`
do
  echo "Compiling ${file} ..."
  msgfmt -o ${file/.po/.mo} $file
done

echo "Done!"
