#!/bin/bash
##
# Import wordpress DB from .vagrant folder
##

# Stop on errors
set -e

# Source environment if doesn't exist yet
if [ -z $PS1 ]; then
  source /etc/container_environment.sh
fi

#import database with mysql tool
/usr/bin/mysql -u $DB_USER --password=$DB_PASSWORD $DB_NAME < "$WP_PROJECT/.vagrant/shutdown-dump.sql"
if [ $? -eq 0 ]; then
    echo -e "\e[92mSuccess:\e[0m Database was imported correctly!"
fi