#!/bin/bash

# Stop on error
set -e

# Source environment if doesn't exist yet
if [ -z $PS1 ]; then
  source /etc/container_environment.sh
fi

if [ -f /data/wordpress/scripts/run-tests ]; then #try run-tests script
  bash /data/wordpress/scripts/run-tests
elif [ -f /data/wordpress/tests/rspec/test.rb ]; then #try client rspec tests
  /usr/local/bin/rspec /data/wordpress/tests/rspec/test.rb
else
  echo "tests not found :(..."
  exit 1
fi